builds:
  - main: ./cmd/addendum
    binary: addendum
    ldflags:
      - -s -w -X github.com/frantjc/dockerfile-addendum.Semver={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
changelog:
  use: github
  filters:
    exclude:
      - merge conflict
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
dockers:
  - image_templates:
      - ghcr.io/logsquaredn/dockerfile-addendum:{{ .Version }}
      - ghcr.io/logsquaredn/dockerfile-addendum:{{ .Major }}.{{ .Minor }}
      - ghcr.io/logsquaredn/dockerfile-addendum:{{ .Major }}
      - ghcr.io/logsquaredn/dockerfile-addendum:latest
